---
driver:
  name: vagrant
  vm_hostname: 'mylbr'
  network:
    - ["private_network", {ip: "192.168.3.2"}]

provisioner:
  name: chef_solo
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true
  require_chef_omnibus: 12.19.36

verifier:
  name: inspec

platforms:
  - name: centos-6.8

suites:
  - name: default
    run_list:
      - recipe[mylbr::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
